nums=[5,6,3,8,10,11,12,15,16,18,50,20]
for n in nums:
    if(n%2==0):
        print(n)

name="chetan paudel"
address="surkhet"
college="Banke Bageshwari campus"

student=[{
    name:"chetan",
    address:"surkhet",
    college:"Banke bageshwari",
},
{
 name:"sudip",
    address:"parbat",
    college:"Banke bageshwari",   
}]

# for i in range(0,len(student)):
#     print(f"My name is {student[i].name}. Iam from {student[i].address}, My college name is {student[i].college}")






# string="Banke Bageshwari Campus nepalgunj Banke"
# print(string.count("Banke"))

a="someone"
print(type(a))



str="Banke bageshwori campus, nepalgunj, banke"
print(str.lower().count("b"))

print(len(str))
print(str.title())
